name: Build
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: windows-2019
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: build
        shell: pwsh
        run: |
          . build.ps1
